# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('style_name', models.CharField(max_length=120, verbose_name='Название стиля')),
            ],
        ),
    ]
