# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-16 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crew_name', models.CharField(max_length=120, verbose_name='Название команды')),
            ],
        ),
    ]
