# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-16 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pydb', '0003_auto_20200316_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Styles',
            new_name='Style',
        ),
    ]
